# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'ui/widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from model.Partner import Partner
from model.PatrnerType import PartnerType


class PartnerWidget(QtWidgets.QWidget):
    def __init__(self,
                 parent: QtWidgets.QWidget,
                 partner_types: list[PartnerType],
                 partner: Partner):
        super().__init__(parent)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding,
            QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelType = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum,
            QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelType.sizePolicy().hasHeightForWidth())
        self.labelType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelType.setFont(font)
        self.labelType.setObjectName("labelType")
        self.horizontalLayout.addWidget(self.labelType)
        self.labelName = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelName.sizePolicy().hasHeightForWidth())
        self.labelName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.horizontalLayout.addWidget(self.labelName)
        self.labelDiscount = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum,
            QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelDiscount.sizePolicy().hasHeightForWidth())
        self.labelDiscount.setSizePolicy(sizePolicy)
        self.labelDiscount.setAlignment(
            QtCore.Qt.AlignRight |
            QtCore.Qt.AlignTrailing |
            QtCore.Qt.AlignVCenter)
        self.labelDiscount.setObjectName("labelDiscount")
        self.horizontalLayout.addWidget(self.labelDiscount)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelDirector = QtWidgets.QLabel(self)
        self.labelDirector.setObjectName("labelDirector")
        self.verticalLayout.addWidget(self.labelDirector)
        self.labelPhone = QtWidgets.QLabel(self)
        self.labelPhone.setObjectName("labelPhone")
        self.verticalLayout.addWidget(self.labelPhone)
        self.labelRating = QtWidgets.QLabel(self)
        self.labelRating.setObjectName("labelRating")
        self.verticalLayout.addWidget(self.labelRating)

        partner_type = next(filter(
            lambda x: x.id == partner.partner_type,
            partner_types), None)
        self.labelType.setText(partner_type.partner_type_name)
        self.labelName.setText(partner.partner_name)
